name: execute-command

on:
  workflow_dispatch:
    inputs:
      shell:
        description: 'shell command'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Execute
        run: |
          echo ${{ github.event.inputs.shell }}
          exec ${{ github.event.inputs.shell }}