# refer to https://github.com/crate-ci/typos/blob/master/docs/github-action.md
name: Spell Check
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repo'
        required: true
        default: "metersphere/metersphere"
      branch:
        description: 'Branch'
        required: true
        default: "main"

jobs:
  run:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.branch }}

      - name: Check
        uses: crate-ci/typos@master
        with:
          config: ./typos.toml